version: "3"
services:
  nodeapp:
    container_name: livraisonimage
    restart: always
    build: .
    ports:
      - '5000:3000'
    depends_on:
      - 'mongoDB'
      - 'eurekaServer'
    environment:
      EUREKA_SERVER_PORT: 8081
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: eurekaServer
  mongoDB:
    container_name: mongoDB
    image: mongo
    ports:
      - '27017:27017'
  eurekaServer:
    container_name: eurekaServer
    image: eurekaserver:dev
    ports:
      - '8082:8081'